name: Check vulnerabilities

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON'

jobs:
  check:
    timeout-minutes: 2
    name: Check Vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install pip and pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Check Vulnerabilities
        run: |
          pipenv check
