name: Dev Workflow

on:
  push:
    branches:
      - develop
    paths:
      - '**.py'
      - '*/workflows/*.yml'
      - 'Pipfile'
      - 'Pipfile.lock'

jobs:
  quality:
    timeout-minutes: 5
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: pipenv
    - name: Install pip and pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    - name: Install dependencies
      run: |
        pipenv install --dev
    - name: Analysing the code with pylint
      run: |
        pipenv run pylint $(git ls-files formify/*.py) --rcfile .pylintrc --fail-under=8
