name: Main Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "ERROR: You can only merge to main from dev."
          exit 1
  quality:
    needs: [check_branch]
    timeout-minutes: 5
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files src/*.py) --fail-under=8
